services:
  ollama:
    image: meowsaytounge/llaravellama-ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama-models:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, compute, utility]

  llaravellama:
    image: meowsaytounge/llaravellama:latest
    ports:
      - "80:80"
    environment:
      - OLLAMA_HOST=ollama
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      - ollama

volumes:
  ollama-models: