services:
  ollama:
    build:
      context: .
      dockerfile: docker/Dockerfile.ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-models:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, compute, utility]
  llaravellama:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "80:80"
    environment:
      - OLLAMA_HOST=ollama
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - app-storage:/var/www/html/storage/app/data
    depends_on:
      - ollama

volumes:
  ollama-models:
  app-storage: