services:
  ollama:
    build:
      context: .
      dockerfile: docker/Dockerfile.ollama.modals
    ports:
      - "11434:11434"
    volumes:
      - ollama-models:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
  llaravellama:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "80:80"
    environment:
      - OLLAMA_HOST=ollama
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      - ollama
volumes:
  ollama-models: